module.exports.default = [ 
  { name: 'aristotle_onassis',
    quote: 'Find a priest who understands English and doesn\'t look like Rasputin.',
    Time: '22 : 48',
    Date: 'August 4th 2014',
    Votes: 0 },
  { name: 'w_somerset_maugham',
    quote: 'When I read a book I seem to read it with my eyes only, but now and then I come across a passage, perhaps only a phrase, which has a meaning for me, and it becomes part of me.',
    Time: '22 : 48',
    Date: 'August 4th 2014',
    Votes: 0 },
  { name: 'richard_bach',
    quote: 'What the caterpillar calls the end of the world the master calls a butterfly.',
    Time: '22 : 48',
    Date: 'August 4th 2014',
    Votes: 0 },
  { name: 'mitt_romney',
    quote: 'And the American people are the greatest people in the world. What makes America the greatest nation in the world is the heart of the American people: hardworking, innovative, risk-taking, God- loving, family-oriented American people.',
    Time: '22 : 48',
    Date: 'August 4th 2014',
    Votes: 0 },
  { name: 'miguel_angel_ruiz',
    quote: 'Respect is one of the greatest expressions of love.',
    Time: '22 : 48',
    Date: 'August 4th 2014',
    Votes: 0 },
  { name: 'henri_nouwen',
    quote: 'Somewhere we know that without silence words lose their meaning, that without listening speaking no longer heals, that without distance closeness cannot cure.',
    Time: '22 : 48',
    Date: 'August 4th 2014',
    Votes: 0 },
  { name: 'abraham_lincoln',
    quote: 'Am I not destroying my enemies when I make friends of them?',
    Time: '22 : 48',
    Date: 'August 4th 2014',
    Votes: 0 },
  { name: 'douglas_adams',
    quote: 'I don\'t believe it. Prove it to me and I still won\'t believe it.',
    Time: '22 : 48',
    Date: 'August 4th 2014',
    Votes: 0 },
  { name: 'charlie_sheen',
    quote: 'I\'m 0 for 3 with marriage - the scoreboard doesn\'t lie, never has. So what we all have is a marriage of the heart. To sully or contaminate or radically disrespect this union with a shameful contract is something that I will leave to the amateurs and the Bible grippers.',
    Time: '22 : 48',
    Date: 'August 4th 2014',
    Votes: 0 },
  { name: 'colin_powell',
    quote: 'It ain\'t as bad as you think. It will look better in the morning.',
    Time: '22 : 48',
    Date: 'August 4th 2014',
    Votes: 0 } 
]